package com.vlms.model;

import com.vlms.enums.NotificationType;
import com.vlms.util.IdGenerator;

import java.time.LocalDateTime;

/**
 * Represents a system notification generated by the NotificationService.
 * Immutable by design: once created, a notification cannot be altered.
 */
public final class Notification {

    private final String notificationId;
    private final NotificationType type;
    private final String message;
    private final String targetEntityId;   // vendorId / contractId etc.
    private final String targetEntityType; // "Vendor" / "Contract" etc.
    private final LocalDateTime createdAt;
    private boolean read;

    public Notification(NotificationType type, String message, String targetEntityId, String targetEntityType) {
        this.notificationId = IdGenerator.generateNotificationId();
        this.type = type;
        this.message = message;
        this.targetEntityId = targetEntityId;
        this.targetEntityType = targetEntityType;
        this.createdAt = LocalDateTime.now();
        this.read = false;
    }

    public void markAsRead() {
        this.read = true;
    }

    // --- Getters ---

    public String getNotificationId() { return notificationId; }
    public NotificationType getType() { return type; }
    public String getMessage() { return message; }
    public String getTargetEntityId() { return targetEntityId; }
    public String getTargetEntityType() { return targetEntityType; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public boolean isRead() { return read; }

    @Override
    public String toString() {
        return String.format("[%s] %s: %s (Entity: %s %s)",
                notificationId, type, message, targetEntityType, targetEntityId);
    }
}
