package com.vlms.enums;

/**
 * Categories of notifications generated by the system.
 */
public enum NotificationType {
    CONTRACT_EXPIRY("Contract is approaching expiry"),
    DOCUMENT_EXPIRY("Document is approaching expiry"),
    VENDOR_APPROVAL("Vendor has been approved"),
    PAYMENT_COMPLETION("Payment has been processed"),
    VENDOR_SUSPENSION("Vendor has been suspended"),
    VENDOR_TERMINATION("Vendor has been terminated"),
    INVOICE_REJECTED("Invoice has been rejected"),
    RISK_ALERT("High risk level detected for vendor");

    private final String description;

    NotificationType(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
